#! /bin/bash
# This script copies files generated by Simulink Embedded Coder to an Android
# application project's JNI folder for use with the Android NDK.
#
# The script accepts the JNI folder's path as first argument.
#
# There is a Matlab script that must be run prior to this script as it will
# generate a file ~/.simulinkfilecopy, which is needed.
#
# Author: laurenz
# Version: 2013-09-06-1

filefile=~/.simulinkfilecopy	# This file has the matlab script output
makefilefile=Android.mk 	# This is the name of the NDK makefile

shopt -s nullglob		# empty loops shouldn't execute http://stackoverflow.com/q/15935806

# Check if jni folder passed
if [ $# != 1 ]; then
	echo "Jni folder path not passed ($# arguments instead of 1 passed)"
	exit 1;
fi

# Check if argument is a directory
if [ ! -d $1 ]; then
	echo "$1 is not a directory"
	exit 2;
fi

# Check if matlab script output exists
if [ ! -e $filefile ]; then
	echo "$filefile not found. Did you run the Matlab script?"
	exit 3;
fi

# Read file contents to array
filearray=( $( < $filefile ) )
echo "Copying files to $1/"
for i in $(seq 0 $((${#filearray[@]} - 1)))
do
	cp ${filearray[$i]} $1 && echo ${filearray[$i]}
done

# Build line with list of c/cpp files in jni folder
newline="LOCAL_SRC_FILES := "
for f in $1/*.c; do
	newline="$newline $( basename $f )"
done
for f in $1/*.cpp; do
	newline="$newline $( basename $f )"
	echo $f
done

# Update makefile
#makefile=$1/$makefilefile
#echo "Updating Makefile $makefile"
#cp $makefile $makefile.tmp
#sed "
#/LOCAL_SRC_FILES/ c\
#${newline}
#" <$makefile.tmp > $makefile
#rm $makefile.tmp


